config/routes.rb
# -*- encoding : utf-8 -*-
Dispen3::Application.routes.draw do
  resources :diag_types
  resources :diag_officials
  resources :motifs
  resources :users
  resources :user_sessions
  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout
  
  match 'consul_diags/find' => 'consul_diags#find'
  match 'consul_diags/rapp' => 'consul_diags#rapp'
  match 'consul_diags/find_offi' => 'consul_diags#find_offi'
  match 'consul_diags/find_date_offi' => 'consul_diags#find_date_offi'
  
  match 'consul_diags/find_date' => 'consul_diags#find_date'
  match 'consultations/:id/new' => 'consultations#new',  :as => :enlace
  get 'consultations/:id' => 'consultations#show',  :as => :enlace2
  match 'search' => 'search#show', :as => :search
  
  
  resources :consul_motifs
  resources :consul_diags do
    post :find_date, :action => "find", :on => :collection
  end
  resources :consul_trats
  resources :diagnostics
  resources :groupe_traitements
  resources :traitements
  resources :tipeconsultations
  resources :communes
  resources :professions
  resources :ethnies
  resources :villages
  resources :sexes
  resources :consultations
  resources :patients
  match 'patients/update_village_select/:id', :controller=>'patients', :action => 'update_village_select'
  root :to => "welcome#index"
end

app/models/commune.rb
# -*- encoding : utf-8 -*-
class Commune < ActiveRecord::Base
  attr_accessible :nom
  has_many :patients
  has_many :villages
  validates  :nom, :presence => true
  validates :nom, :uniqueness => true
  before_destroy :check_for_village_and_patient           
  
  def check_for_village_and_patient
    unless villages.count == 0 && patients.count == 0
      message_info = "Il n'est pas posible eliminer une commune sans eliminer ses x"
      message_info += "villages et" if villages.count != 0 
      message_info += " patients" if patients.count != 0 
      errors.add(:commune, "message_info")
      return false
    end
  end
  
end

app/controllers/communes_controller.rb
# -*- encoding : utf-8 -*-
class CommunesController < ApplicationController
  load_and_authorize_resource
  
  def index    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @communes }
    end 
  end

  def show
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @commune }
    end 
  end

  def new
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @commune }
    end
  end

  def create
    respond_to do |format|
      if @commune.save
        format.html { redirect_to(@commune, :notice => 'La commune a eté creé.') }
        format.xml  { render :xml => @commune, :status => :created, :location => @commune }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @commune.errors, :status => :unprocessable_entity } 
      end
    end  
  end
  
  def edit
  end

  def update
    respond_to do |format|
      if @commune.update_attributes(params[:commune])
        format.html { redirect_to(@commune, :notice => 'La commune a eté mis a jour.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @commune.errors, :status => :unprocessable_entity }
      end
    end  
  end

  def destroy
    if @commune.destroy
        redirect_to(communes_url, :notice => "La commune a eté eliminé.")
    else
      n_mess = 0
      n_mess += 1 if @commune.villages[0]
      n_mess += 2 if @commune.patients[0]
      mes_info = "Il n'est pas posible eliminer une commune sans eliminer ses " 
      mes_info += case n_mess
        when 1 then "villages"
        when 2 then "patients"
        when 3 then "patients et ses villages"
      end  
      redirect_to(communes_url, :alert => mes_info)
    end
  end
end

app/helpers/communes_helper.rb
# -*- encoding : utf-8 -*-
module CommunesHelper
end

app/views/communes/_form.html.erb
<%= form_for(@commune) do |f| %>
  <% if @commune.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@commune.errors.count, "error") %> C'est defendu cette commune d'etre gardée:</h2>

      <ul>
      <% @commune.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nom %><br />
    <%= f.text_field :nom %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/communes/edit.html.erb
<% title "Edit Commune" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @commune %> |
  <%= link_to "View All", communes_path %>
</p>

app/views/communes/index.html.erb
<% title "Communes" %>

<table>
  <tr>
    <th>Nom</th>
  </tr>
  <% for commune in @communes %>
    <tr>
      <td><%= commune.nom %></td>
      <td><%= link_to "Show", commune %></td>
      <td><%= link_to "Edit", edit_commune_path(commune) %></td>
      <td><%= link_to "Destroy", commune, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Commune", new_commune_path %></p>

app/views/communes/new.html.erb
<% title "New Commune" %>

<%= render 'form' %>

<p><%= link_to "Back to List", communes_path %></p>

app/views/communes/show.html.erb
<% title "Commune" %>

<p>
  <strong>Nom:</strong>
  <%= @commune.nom %>
</p>

<p>
  <%= link_to "Edit", edit_commune_path(@commune) %> |
  <%= link_to "Destroy", @commune, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", communes_path %>
</p>