config/routes.rb
# -*- encoding : utf-8 -*-
Dispen3::Application.routes.draw do
  resources :diag_types
  resources :diag_officials
  resources :motifs
  resources :users
  resources :user_sessions
  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout
  
  match 'consul_diags/find' => 'consul_diags#find'
  match 'consul_diags/rapp' => 'consul_diags#rapp'
  match 'consul_diags/find_offi' => 'consul_diags#find_offi'
  match 'consul_diags/find_date_offi' => 'consul_diags#find_date_offi'
  
  match 'consul_diags/find_date' => 'consul_diags#find_date'
  match 'consultations/:id/new' => 'consultations#new',  :as => :enlace
  get 'consultations/:id' => 'consultations#show',  :as => :enlace2
  match 'search' => 'search#show', :as => :search
  
  
  resources :consul_motifs
  resources :consul_diags do
    post :find_date, :action => "find", :on => :collection
  end
  resources :consul_trats
  resources :diagnostics
  resources :groupe_traitements
  resources :traitements
  resources :tipeconsultations
  resources :communes
  resources :professions
  resources :ethnies
  resources :villages
  resources :sexes
  resources :consultations
  resources :patients
  match 'patients/update_village_select/:id', :controller=>'patients', :action => 'update_village_select'
  root :to => "welcome#index"
end

app/models/consul_motif.rb
# -*- encoding : utf-8 -*-
class ConsulMotif < ActiveRecord::Base
  attr_accessible :consultation_id, :motif_id
  belongs_to :motif
  belongs_to :consultation

  #validates  :consultation_id, :presence => true
  validates  :motif_id, :presence => true
  attr_accessor :motif_name
  
  def motif_name
    self.motif.description if self.motif
  end
  def self.find_motif
    tot_motif=ConsulMotif.all
    motif_dic=Hash.new(0)
    tot_motif.each do |h|
      motif_dic[h.motif_id] += 1
    end
    motif_dic  
  end
end

app/views/consul_motifs/_form.html.erb
<%= form_for @consul_motif do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :consultation_id %><br />
    <%= f.text_field :consultation_id %>
  </p>
  <p>
    <%= f.label :motif_id %><br />
    <%= f.text_field :motif_id %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/consul_motifs/edit.html.erb
<% title "Edit Consul Motif" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @consul_motif %> |
  <%= link_to "View All", consul_motifs_path %>
</p>

app/views/consul_motifs/index.html.erb
<% title "Consul Motifs" %>
<table>
  <tr>
    <th>Consultation</th>
    <th>Acronime</th>
    <th>Motif</th>
  </tr>
  <% for consul_motif in @consul_motifs %>
    <tr>
      <td><%= consul_motif.consultation_id %></td>
      <td><%= consul_motif.motif.description %></td>
      <td><%= link_to "Show", consul_motif %></td>
      <td><%= link_to "Edit", edit_consul_motif_path(consul_motif) %></td>
      <td><%= link_to "Destroy", consul_motif, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Consul Motif", new_consul_motif_path %></p>

app/views/consul_motifs/new.html.erb
<% title "New Consul Motif" %>

<%= render 'form' %>

<p><%= link_to "Back to List", consul_motifs_path %></p>

app/views/consul_motifs/show.html.erb
<% title "Consul Motif" %>

<p>
  <strong>Consultation:</strong>
  <%= @consul_motif.consultation_id %>
</p>
<p>
  <strong>Motif</strong>
  <%= @consul_motif.motif_id %>
</p>

<p>
  <%= link_to "Edit", edit_consul_motif_path(@consul_motif) %> |
  <%= link_to "Destroy", @consul_motif, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", consul_motifs_path %>
</p>