config/routes.rb
# -*- encoding : utf-8 -*-
Dispen3::Application.routes.draw do
  resources :diag_types
  resources :diag_officials
  resources :motifs
  resources :users
  resources :user_sessions
  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout
  
  match 'consul_diags/find' => 'consul_diags#find'
  match 'consul_diags/rapp' => 'consul_diags#rapp'
  match 'consul_diags/find_offi' => 'consul_diags#find_offi'
  match 'consul_diags/find_date_offi' => 'consul_diags#find_date_offi'
  
  match 'consul_diags/find_date' => 'consul_diags#find_date'
  match 'consultations/:id/new' => 'consultations#new',  :as => :enlace
  get 'consultations/:id' => 'consultations#show',  :as => :enlace2
  match 'search' => 'search#show', :as => :search
  
  
  resources :consul_motifs
  resources :consul_diags do
    post :find_date, :action => "find", :on => :collection
  end
  resources :consul_trats
  resources :diagnostics
  resources :groupe_traitements
  resources :traitements
  resources :tipeconsultations
  resources :communes
  resources :professions
  resources :ethnies
  resources :villages
  resources :sexes
  resources :consultations
  resources :patients
  match 'patients/update_village_select/:id', :controller=>'patients', :action => 'update_village_select'
  root :to => "welcome#index"
end

app/models/village.rb
# -*- encoding : utf-8 -*-
class Village < ActiveRecord::Base
  attr_accessible :nom, :commune_id
  has_many :patients
  belongs_to :commune
  validates  :nom, :presence => true
  validates_uniqueness_of :nom, :scope => :commune_id, :message => 'Le pair Commune-Village doit être unique'
    def must_be_unique
      if self.class.where(nom: nom, commune_id: commune_id).exists?
        errors.add(:base, 'Le pair Commune-Village doit être unique')
      end
    end
    before_destroy :check_for_patient
    def check_for_patient
      unless patients.count == 0
        message_info = "Il n'est pas posible eliminer une commune sans eliminer ses patients"
        errors.add(:nom, "message_info")
        return false
      end
    end    
end

app/controllers/villages_controller.rb
# -*- encoding : utf-8 -*-
class VillagesController < ApplicationController
  load_and_authorize_resource
  
  def index
  end

  def show
  end

  def new
  end

  def create
    if @village.save
      redirect_to @village, :notice => "Successfully created village."
    else
      render :action => 'new'
    end
  end

  def edit
  end

  def update
    if @village.update_attributes(params[:village])
      redirect_to @village, :notice  => "Successfully updated village."
    else
      render :action => 'edit'
    end
  end
  def destroy
    if @village.destroy
        redirect_to(villages_url, :notice => "Le village a eté eliminé.")
    else
      mes_info = "Il n'est pas posible eliminer un village sans eliminer ses patients" 
      redirect_to(villages_url, :alert => mes_info)
    end
  end
end

app/helpers/villages_helper.rb
# -*- encoding : utf-8 -*-
module VillagesHelper
end

app/views/villages/_form.html.erb
<%= form_for(@village) do |f| %>
  <% if @village.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@village.errors.count, "error") %> prohibited this village from being saved:</h2>

      <ul>
      <% @village.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nom %><br />
    <%= f.text_field :nom %>
  </div>
  <div class="field">
    <%= f.label :commune_id %><br />
    <%= f.text_field :commune_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/villages/edit.html.erb
<% title "Edit Village" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @village %> |
  <%= link_to "View All", villages_path %>
</p>

app/views/villages/index.html.erb
<% title "Villages" %>

<table>
  <tr>
    <th>Nom</th>
    <th>Commune</th>
  </tr>
  <% for village in @villages %>
    <tr>
      <td><%= village.nom %></td>
      <td><%= village.commune_id %></td>
      <td><%= link_to "Show", village %></td>
      <td><%= link_to "Edit", edit_village_path(village) %></td>
      <td><%= link_to "Destroy", village, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Village", new_village_path %></p>

app/views/villages/new.html.erb
<% title "New Village" %>

<%= render 'form' %>

<p><%= link_to "Back to List", villages_path %></p>

app/views/villages/show.html.erb
<% title "Village" %>

<p>
  <strong>Nom:</strong>
  <%= @village.nom %>
</p>
<p>
  <strong>Commune:</strong>
  <%= @village.commune_id %>
</p>

<p>
  <%= link_to "Edit", edit_village_path(@village) %> |
  <%= link_to "Destroy", @village, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", villages_path %>
</p>