config/routes.rb
# -*- encoding : utf-8 -*-
Dispen3::Application.routes.draw do
  resources :diag_types
  resources :diag_officials
  resources :motifs
  resources :users
  resources :user_sessions
  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout
  
  match 'consul_diags/find' => 'consul_diags#find'
  match 'consul_diags/rapp' => 'consul_diags#rapp'
  match 'consul_diags/find_offi' => 'consul_diags#find_offi'
  match 'consul_diags/find_date_offi' => 'consul_diags#find_date_offi'
  
  match 'consul_diags/find_date' => 'consul_diags#find_date'
  match 'consultations/:id/new' => 'consultations#new',  :as => :enlace
  get 'consultations/:id' => 'consultations#show',  :as => :enlace2
  match 'search' => 'search#show', :as => :search
  
  
  resources :consul_motifs
  resources :consul_diags do
    post :find_date, :action => "find", :on => :collection
  end
  resources :consul_trats
  resources :diagnostics
  resources :groupe_traitements
  resources :traitements
  resources :tipeconsultations
  resources :communes
  resources :professions
  resources :ethnies
  resources :villages
  resources :sexes
  resources :consultations
  resources :patients
  match 'patients/update_village_select/:id', :controller=>'patients', :action => 'update_village_select'
  root :to => "welcome#index"
end

app/controllers/diag_types_controller.rb
class DiagTypesController < ApplicationController
  # GET /diag_types
  # GET /diag_types.xml
  def index
    @diag_types = DiagType.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @diag_types }
    end
  end

  # GET /diag_types/1
  # GET /diag_types/1.xml
  def show
    @diag_type = DiagType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @diag_type }
    end
  end

  # GET /diag_types/new
  # GET /diag_types/new.xml
  def new
    @diag_type = DiagType.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @diag_type }
    end
  end

  # GET /diag_types/1/edit
  def edit
    @diag_type = DiagType.find(params[:id])
  end

  # POST /diag_types
  # POST /diag_types.xml
  def create
    @diag_type = DiagType.new(params[:diag_type])

    respond_to do |format|
      if @diag_type.save
        format.html { redirect_to(@diag_type, :notice => 'Diag type was successfully created.') }
        format.xml  { render :xml => @diag_type, :status => :created, :location => @diag_type }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @diag_type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /diag_types/1
  # PUT /diag_types/1.xml
  def update
    @diag_type = DiagType.find(params[:id])

    respond_to do |format|
      if @diag_type.update_attributes(params[:diag_type])
        format.html { redirect_to(@diag_type, :notice => 'Diag type was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @diag_type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /diag_types/1
  # DELETE /diag_types/1.xml
  def destroy
    @diag_type = DiagType.find(params[:id])
    @diag_type.destroy

    respond_to do |format|
      format.html { redirect_to(diag_types_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/diag_types_helper.rb
module DiagTypesHelper
end

app/views/diag_types/_form.html.erb
<%= form_for(@diag_type) do |f| %>
  <% if @diag_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@diag_type.errors.count, "error") %> prohibited this diag_type from being saved:</h2>

      <ul>
      <% @diag_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/diag_types/edit.html.erb
<h1>Editing diag_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @diag_type %> |
<%= link_to 'Back', diag_types_path %>

app/views/diag_types/index.html.erb
<h1>Listing diag_types</h1>

<table>
  <tr>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @diag_types.each do |diag_type| %>
  <tr>
    <td><%= diag_type.description %></td>
    <td><%= link_to 'Show', diag_type %></td>
    <td><%= link_to 'Edit', edit_diag_type_path(diag_type) %></td>
    <td><%= link_to 'Destroy', diag_type, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Diag type', new_diag_type_path %>

app/views/diag_types/new.html.erb
<h1>New diag_type</h1>

<%= render 'form' %>

<%= link_to 'Back', diag_types_path %>

app/views/diag_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Description:</b>
  <%= @diag_type.description %>
</p>


<%= link_to 'Edit', edit_diag_type_path(@diag_type) %> |
<%= link_to 'Back', diag_types_path %>